// <auto-generated />
using DeeGoldHealthPlus.models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeeGoldHealthPlus.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200125103626_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DeeGoldHealthPlus.models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "General"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "WellBeing"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Treatment"
                        });
                });

            modelBuilder.Entity("DeeGoldHealthPlus.models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProductOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 2,
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            IsProductOfTheWeek = true,
                            LongDescription = "Rich in Omega 3,6,7 & 9 Protects the liver, heart and kidney",
                            Price = 13100.00m,
                            ProductName = "Longrich BerryOil",
                            ShortDescription = "Shenxing Seabuckthorn"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/blueberrycheesecake.jpg",
                            IsProductOfTheWeek = false,
                            LongDescription = "It is a very good dietary option containing detoxifier and anti-carcinogens",
                            Price = 2950.00m,
                            ProductName = "Longrich GreenTea",
                            ShortDescription = "Xinchang Tea"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 2,
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cheesecake.jp",
                            IsProductOfTheWeek = false,
                            LongDescription = "Increases fat burning and improves physical performance",
                            Price = 2950.00m,
                            ProductName = "Longrich Slimming Tea",
                            ShortDescription = "Slimming/Pink Tea"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cherrypie.jpg",
                            IsProductOfTheWeek = false,
                            LongDescription = "Increases fat burning and improves physical performance",
                            Price = 7800.00m,
                            ProductName = "Longrich Vintage Wine",
                            ShortDescription = "100% Natural & Medicinal"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/christmasapplepie.jpg",
                            IsProductOfTheWeek = false,
                            LongDescription = "It corrects hormonal imbalance, it is anti-aging",
                            Price = 9800.00m,
                            ProductName = "Longrich Mengquian",
                            ShortDescription = "Fertility Supplement for Women"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 3,
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cranberrypie.jpg",
                            IsProductOfTheWeek = false,
                            LongDescription = "Effective in the treatment of stroke,athritis and rheumatism and also helps to boost the immune system",
                            Price = 9000.00m,
                            ProductName = "Longrich Arthro SupReviver",
                            ShortDescription = "UNISEX"
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/peachpie.jpg",
                            IsProductOfTheWeek = false,
                            LongDescription = "A mouth spuray to keep your breath fresh, and your healthy",
                            Price = 1100.00m,
                            ProductName = "Longrich Mouth Freshner",
                            ShortDescription = "Keeps your mouth fresh and health"
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 3,
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinpie.jpg",
                            IsProductOfTheWeek = true,
                            LongDescription = "Treats over 200 diseases",
                            Price = 25000.00m,
                            ProductName = "PhytoScience Stem-cell",
                            ShortDescription = "Double Stemcell"
                        });
                });

            modelBuilder.Entity("DeeGoldHealthPlus.models.Product", b =>
                {
                    b.HasOne("DeeGoldHealthPlus.models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
